import type { DiagramSpec } from "./types";

const diagramDrafts = [
  {
    id: "project-borrow-me",
    title: "BorrowMe가 두 시기에 걸쳐 바뀐 범위",
    caption:
      "2024년 팀 제품의 알림 흐름과 2026년 개인 회귀 검증을 같은 시기로 섞지 않습니다.",
    sourceIds: [
      "borrow-comment-notification-commit",
      "borrow-rest-notification-commit",
      "borrow-team-demo",
      "borrow-query-guard",
      "borrow-stock-invariant",
    ],
    nodes: [
      {
        id: "comment",
        label: "Comment",
        detail: "팀 제품의 사용자 행동",
        x: 5,
        y: 34,
        width: 19,
        compact: { x: 8, y: 10, width: 84 },
        sourceIds: ["borrow-comment-notification-commit"],
      },
      {
        id: "notification",
        label: "Notification API",
        detail: "댓글 기반 알림·REST",
        x: 29,
        y: 34,
        width: 22,
        compact: { x: 8, y: 30, width: 84 },
        sourceIds: [
          "borrow-comment-notification-commit",
          "borrow-rest-notification-commit",
        ],
        tone: "accent",
      },
      {
        id: "frontend",
        label: "Team client",
        detail: "연동·시연",
        x: 57,
        y: 12,
        width: 18,
        compact: { x: 8, y: 50, width: 84 },
        sourceIds: ["borrow-rest-notification-commit", "borrow-team-demo"],
        tone: "success",
      },
      {
        id: "query",
        label: "Query guard",
        detail: "목록 SQL 상한",
        x: 57,
        y: 56,
        width: 18,
        compact: { x: 8, y: 70, width: 84 },
        sourceIds: ["borrow-query-guard"],
      },
      {
        id: "stock",
        label: "Stock invariant",
        detail: "동시 예약 회귀",
        x: 80,
        y: 56,
        width: 18,
        compact: { x: 8, y: 90, width: 84 },
        sourceIds: ["borrow-stock-invariant"],
      },
    ],
    edges: [
      {
        id: "comment-notification",
        from: "comment",
        to: "notification",
        label: "creates",
        sourceIds: ["borrow-comment-notification-commit"],
      },
      {
        id: "notification-frontend",
        from: "notification",
        to: "frontend",
        label: "2024 REST",
        sourceIds: ["borrow-rest-notification-commit", "borrow-team-demo"],
      },
      {
        id: "notification-query",
        from: "notification",
        to: "query",
        label: "2026 revisit",
        sourceIds: ["borrow-query-guard"],
      },
      {
        id: "query-stock",
        from: "query",
        to: "stock",
        label: "regression",
        sourceIds: ["borrow-query-guard", "borrow-stock-invariant"],
      },
    ],
    mobileSteps: [
      {
        text: "2024년 댓글 알림과 REST endpoint를 팀 클라이언트에 연결했습니다.",
        sourceIds: [
          "borrow-comment-notification-commit",
          "borrow-rest-notification-commit",
          "borrow-team-demo",
        ],
      },
      {
        text: "2026년 개인적으로 같은 저장소를 다시 검토했습니다.",
        sourceIds: ["borrow-query-guard", "borrow-stock-invariant"],
      },
      {
        text: "현재 조회 SQL 상한과 재고 불변식을 회귀 테스트로 남겼습니다.",
        sourceIds: ["borrow-query-guard", "borrow-stock-invariant"],
      },
    ],
  },
  {
    id: "project-concert-booking",
    title: "사용자가 경험하는 예약 경계",
    caption:
      "Queue는 입장 권한, Booking은 예약 의도, PostgreSQL은 좌석의 최종 상태를 맡습니다.",
    sourceIds: [
      "concert-queue-token-test",
      "concert-product-journey-e2e",
      "concert-seat-release-e2e",
      "concert-seat-contention-test",
      "concert-idempotency-test",
      "concert-outbox-test",
      "concert-dlt-test",
    ],
    nodes: [
      {
        id: "web",
        label: "Booking client",
        detail: "대기·선택·복구",
        x: 4,
        y: 34,
        width: 20,
        compact: { x: 8, y: 10, width: 84 },
        sourceIds: ["concert-product-journey-e2e", "concert-seat-release-e2e"],
        tone: "accent",
      },
      {
        id: "queue",
        label: "Redis Queue",
        detail: "user + schedule token",
        x: 29,
        y: 12,
        width: 19,
        compact: { x: 8, y: 26, width: 84 },
        sourceIds: ["concert-queue-token-test", "concert-product-journey-e2e"],
      },
      {
        id: "booking",
        label: "Booking service",
        detail: "idempotency + lock",
        x: 29,
        y: 56,
        width: 19,
        compact: { x: 8, y: 42, width: 84 },
        sourceIds: ["concert-idempotency-test", "concert-seat-contention-test"],
      },
      {
        id: "db",
        label: "PostgreSQL",
        detail: "seat + reservation",
        x: 55,
        y: 56,
        width: 18,
        compact: { x: 8, y: 58, width: 84 },
        sourceIds: ["concert-seat-contention-test", "concert-seat-release-e2e"],
        tone: "success",
      },
      {
        id: "outbox",
        label: "Outbox",
        detail: "commit 이후 사건",
        x: 79,
        y: 34,
        width: 17,
        compact: { x: 8, y: 74, width: 84 },
        sourceIds: ["concert-outbox-test"],
      },
      {
        id: "kafka",
        label: "Kafka / DLT",
        detail: "발행·격리·replay",
        x: 55,
        y: 12,
        width: 18,
        compact: { x: 8, y: 90, width: 84 },
        sourceIds: ["concert-outbox-test", "concert-dlt-test"],
      },
    ],
    edges: [
      {
        id: "web-queue",
        from: "web",
        to: "queue",
        label: "enter",
        sourceIds: ["concert-queue-token-test", "concert-product-journey-e2e"],
      },
      {
        id: "web-booking",
        from: "web",
        to: "booking",
        label: "reserve",
        sourceIds: ["concert-idempotency-test", "concert-product-journey-e2e"],
      },
      {
        id: "queue-booking",
        from: "queue",
        to: "booking",
        label: "bound token",
        sourceIds: ["concert-queue-token-test", "concert-product-journey-e2e"],
      },
      {
        id: "booking-db",
        from: "booking",
        to: "db",
        label: "commit",
        sourceIds: ["concert-seat-contention-test", "concert-idempotency-test"],
      },
      {
        id: "db-outbox",
        from: "db",
        to: "outbox",
        label: "same transaction",
        sourceIds: ["concert-outbox-test"],
      },
      {
        id: "outbox-kafka",
        from: "outbox",
        to: "kafka",
        label: "retry publish",
        sourceIds: ["concert-outbox-test"],
      },
    ],
    mobileSteps: [
      {
        text: "클라이언트가 일정별 Queue Token을 발급받습니다.",
        sourceIds: ["concert-queue-token-test", "concert-product-journey-e2e"],
      },
      {
        text: "예약 의도는 Idempotency-Key로 재시도돼도 한 결과로 수렴합니다.",
        sourceIds: ["concert-idempotency-test", "concert-product-journey-e2e"],
      },
      {
        text: "PostgreSQL transaction이 좌석의 최종 승자를 정합니다.",
        sourceIds: ["concert-seat-contention-test"],
      },
      {
        text: "commit 이후 사건은 Outbox와 Kafka 복구 경로로 이동합니다.",
        sourceIds: ["concert-outbox-test", "concert-dlt-test"],
      },
    ],
  },
  {
    id: "project-realtime-chat",
    title: "저장된 메시지만 상대에게 전달하는 구조",
    caption:
      "실시간 fan-out과 reconnect sync가 같은 persisted message ID를 기준으로 만납니다.",
    sourceIds: [
      "realtime-subscribe-auth-test",
      "realtime-ordering-test",
      "realtime-lifecycle-refactor-commit",
      "realtime-client-state-test",
      "realtime-persistence-boundary-test",
      "realtime-redelivery-test",
      "realtime-persisted-ack-test",
      "realtime-lifecycle-e2e",
      "realtime-sync-api-test",
    ],
    nodes: [
      {
        id: "sender",
        label: "Sender client",
        detail: "optimistic state",
        x: 4,
        y: 34,
        width: 18,
        compact: { x: 8, y: 10, width: 84 },
        sourceIds: [
          "realtime-client-state-test",
          "realtime-persisted-ack-test",
          "realtime-lifecycle-e2e",
        ],
        tone: "accent",
      },
      {
        id: "stomp",
        label: "STOMP gateway",
        detail: "auth + membership",
        x: 27,
        y: 34,
        width: 19,
        compact: { x: 8, y: 26, width: 84 },
        sourceIds: ["realtime-subscribe-auth-test", "realtime-lifecycle-e2e"],
      },
      {
        id: "kafka",
        label: "Kafka",
        detail: "room partition",
        x: 52,
        y: 12,
        width: 17,
        compact: { x: 8, y: 42, width: 84 },
        sourceIds: [
          "realtime-ordering-test",
          "realtime-lifecycle-refactor-commit",
          "realtime-redelivery-test",
        ],
      },
      {
        id: "persistence",
        label: "Persistence",
        detail: "commit then publish",
        x: 52,
        y: 56,
        width: 17,
        compact: { x: 8, y: 58, width: 84 },
        sourceIds: [
          "realtime-lifecycle-refactor-commit",
          "realtime-persistence-boundary-test",
          "realtime-redelivery-test",
        ],
      },
      {
        id: "db",
        label: "Database",
        detail: "message ID",
        x: 76,
        y: 56,
        width: 18,
        compact: { x: 8, y: 74, width: 84 },
        sourceIds: [
          "realtime-persistence-boundary-test",
          "realtime-sync-api-test",
        ],
        tone: "success",
      },
      {
        id: "receiver",
        label: "Receiver client",
        detail: "live + sync",
        x: 76,
        y: 12,
        width: 18,
        compact: { x: 8, y: 90, width: 84 },
        sourceIds: [
          "realtime-client-state-test",
          "realtime-lifecycle-e2e",
          "realtime-sync-api-test",
        ],
      },
    ],
    edges: [
      {
        id: "sender-stomp",
        from: "sender",
        to: "stomp",
        label: "SEND",
        sourceIds: ["realtime-client-state-test", "realtime-lifecycle-e2e"],
      },
      {
        id: "stomp-kafka",
        from: "stomp",
        to: "kafka",
        label: "room key",
        sourceIds: ["realtime-ordering-test", "realtime-lifecycle-e2e"],
      },
      {
        id: "kafka-persistence",
        from: "kafka",
        to: "persistence",
        label: "consume",
        sourceIds: [
          "realtime-lifecycle-refactor-commit",
          "realtime-persistence-boundary-test",
        ],
      },
      {
        id: "persistence-db",
        from: "persistence",
        to: "db",
        label: "commit",
        sourceIds: ["realtime-persistence-boundary-test"],
      },
      {
        id: "persistence-receiver",
        from: "persistence",
        to: "receiver",
        label: "broadcast",
        sourceIds: [
          "realtime-persistence-boundary-test",
          "realtime-redelivery-test",
          "realtime-lifecycle-e2e",
        ],
      },
      {
        id: "db-receiver",
        from: "db",
        to: "receiver",
        label: "reconnect sync",
        sourceIds: ["realtime-sync-api-test", "realtime-lifecycle-e2e"],
      },
    ],
    mobileSteps: [
      {
        text: "STOMP SEND를 roomId key로 Kafka에 기록합니다.",
        sourceIds: ["realtime-ordering-test", "realtime-lifecycle-e2e"],
      },
      {
        text: "Persistence transaction이 DB message ID를 만든 뒤 commit합니다.",
        sourceIds: ["realtime-persistence-boundary-test"],
      },
      {
        text: "commit된 payload만 상대와 발신자에게 broadcast합니다.",
        sourceIds: [
          "realtime-persistence-boundary-test",
          "realtime-persisted-ack-test",
          "realtime-lifecycle-e2e",
        ],
      },
      {
        text: "재연결 client는 마지막 DB ID 이후를 sync합니다.",
        sourceIds: ["realtime-sync-api-test", "realtime-lifecycle-e2e"],
      },
    ],
  },
  {
    id: "project-memory-of-year",
    title: "팀 제품 안에서 직접 맡은 백엔드 범위",
    caption:
      "팀 전체 결과가 아니라 인증에서 앨범 콘텐츠 저장까지의 초기 기반을 표시합니다.",
    sourceIds: [
      "memory-original-contribution",
      "memory-team-demo",
      "memory-current-repository",
      "memory-album-authorization-test",
      "memory-s3-boundary-test",
    ],
    nodes: [
      {
        id: "auth",
        label: "Auth",
        detail: "signup + JWT login",
        x: 5,
        y: 34,
        width: 18,
        compact: { x: 8, y: 10, width: 84 },
        sourceIds: ["memory-original-contribution"],
        tone: "accent",
      },
      {
        id: "user",
        label: "User",
        detail: "identity repository",
        x: 29,
        y: 34,
        width: 18,
        compact: { x: 8, y: 30, width: 84 },
        sourceIds: ["memory-original-contribution"],
      },
      {
        id: "album",
        label: "Album",
        detail: "create + lookup",
        x: 53,
        y: 34,
        width: 18,
        compact: { x: 8, y: 50, width: 84 },
        sourceIds: [
          "memory-original-contribution",
          "memory-album-authorization-test",
        ],
        tone: "success",
      },
      {
        id: "letter",
        label: "Letter",
        detail: "album content",
        x: 77,
        y: 12,
        width: 18,
        compact: { x: 8, y: 70, width: 84 },
        sourceIds: ["memory-original-contribution"],
      },
      {
        id: "photo",
        label: "Photo",
        detail: "upload metadata",
        x: 77,
        y: 56,
        width: 18,
        compact: { x: 8, y: 90, width: 84 },
        sourceIds: ["memory-original-contribution", "memory-s3-boundary-test"],
      },
    ],
    edges: [
      {
        id: "auth-user",
        from: "auth",
        to: "user",
        label: "identifies",
        sourceIds: ["memory-original-contribution"],
      },
      {
        id: "user-album",
        from: "user",
        to: "album",
        label: "owns",
        sourceIds: [
          "memory-original-contribution",
          "memory-album-authorization-test",
        ],
      },
      {
        id: "album-letter",
        from: "album",
        to: "letter",
        label: "contains",
        sourceIds: ["memory-original-contribution"],
      },
      {
        id: "album-photo",
        from: "album",
        to: "photo",
        label: "contains",
        sourceIds: ["memory-original-contribution", "memory-s3-boundary-test"],
      },
    ],
    mobileSteps: [
      {
        text: "회원가입과 JWT 로그인을 통해 사용자를 식별했습니다.",
        sourceIds: ["memory-original-contribution"],
      },
      {
        text: "사용자가 앨범을 생성하고 조회하는 초기 경계를 만들었습니다.",
        sourceIds: [
          "memory-original-contribution",
          "memory-album-authorization-test",
        ],
      },
      {
        text: "앨범 아래 편지와 사진을 저장하는 repository·controller 기반을 연결했습니다.",
        sourceIds: ["memory-original-contribution", "memory-s3-boundary-test"],
      },
    ],
  },
  {
    id: "concert-seat-contention",
    title: "좌석 경합의 세 경계",
    caption: "진입·중복 요청·최종 좌석 상태를 서로 다른 장치가 맡습니다.",
    sourceIds: [
      "concert-queue-token-test",
      "concert-product-journey-e2e",
      "concert-seat-contention-test",
      "concert-idempotency-test",
    ],
    nodes: [
      {
        id: "client",
        label: "Booking intent",
        detail: "stable idempotency key",
        x: 4,
        y: 34,
        width: 20,
        compact: { x: 8, y: 10, width: 84 },
        sourceIds: ["concert-idempotency-test", "concert-product-journey-e2e"],
      },
      {
        id: "queue",
        label: "Queue Token",
        detail: "user + schedule",
        x: 30,
        y: 12,
        width: 19,
        compact: { x: 8, y: 30, width: 84 },
        sourceIds: ["concert-queue-token-test", "concert-product-journey-e2e"],
      },
      {
        id: "orchestrator",
        label: "Reservation",
        detail: "claim + transaction",
        x: 30,
        y: 56,
        width: 19,
        compact: { x: 8, y: 50, width: 84 },
        sourceIds: ["concert-idempotency-test", "concert-seat-contention-test"],
        tone: "accent",
      },
      {
        id: "lock",
        label: "Seat lock",
        detail: "single winner",
        x: 57,
        y: 56,
        width: 18,
        compact: { x: 8, y: 70, width: 84 },
        sourceIds: ["concert-seat-contention-test"],
      },
      {
        id: "db",
        label: "DB constraints",
        detail: "last defense",
        x: 80,
        y: 34,
        width: 18,
        compact: { x: 8, y: 90, width: 84 },
        sourceIds: ["concert-seat-contention-test"],
        tone: "success",
      },
    ],
    edges: [
      {
        id: "client-queue",
        from: "client",
        to: "queue",
        label: "admit",
        sourceIds: ["concert-queue-token-test", "concert-product-journey-e2e"],
      },
      {
        id: "client-orchestrator",
        from: "client",
        to: "orchestrator",
        label: "reserve",
        sourceIds: ["concert-idempotency-test", "concert-product-journey-e2e"],
      },
      {
        id: "queue-orchestrator",
        from: "queue",
        to: "orchestrator",
        label: "validate",
        sourceIds: ["concert-queue-token-test"],
      },
      {
        id: "orchestrator-lock",
        from: "orchestrator",
        to: "lock",
        label: "transaction",
        sourceIds: ["concert-seat-contention-test"],
      },
      {
        id: "lock-db",
        from: "lock",
        to: "db",
        label: "commit",
        sourceIds: ["concert-seat-contention-test"],
      },
    ],
    mobileSteps: [
      {
        text: "Queue Token이 일정별 입장 권한을 확인합니다.",
        sourceIds: ["concert-queue-token-test", "concert-product-journey-e2e"],
      },
      {
        text: "Idempotency-Key가 같은 예약 의도의 재시도를 찾습니다.",
        sourceIds: ["concert-idempotency-test"],
      },
      {
        text: "좌석 lock과 DB constraint가 최종 한 건을 확정합니다.",
        sourceIds: ["concert-seat-contention-test"],
      },
    ],
  },
  {
    id: "concert-event-recovery",
    title: "Outbox와 DLT가 남기는 두 복구 지점",
    caption: "발행 실패와 처리 실패를 다른 상태와 queue에 남깁니다.",
    sourceIds: ["concert-outbox-test", "concert-dlt-test"],
    nodes: [
      {
        id: "transaction",
        label: "Domain transaction",
        detail: "reservation + outbox",
        x: 4,
        y: 34,
        width: 21,
        compact: { x: 8, y: 10, width: 84 },
        sourceIds: ["concert-outbox-test"],
      },
      {
        id: "outbox",
        label: "Outbox",
        detail: "PENDING / FAILED",
        x: 31,
        y: 34,
        width: 18,
        compact: { x: 8, y: 26, width: 84 },
        sourceIds: ["concert-outbox-test"],
        tone: "accent",
      },
      {
        id: "relay",
        label: "Relay",
        detail: "backoff + DEAD",
        x: 55,
        y: 12,
        width: 17,
        compact: { x: 8, y: 42, width: 84 },
        sourceIds: ["concert-outbox-test"],
      },
      {
        id: "kafka",
        label: "Kafka",
        detail: "original topic",
        x: 77,
        y: 12,
        width: 17,
        compact: { x: 8, y: 58, width: 84 },
        sourceIds: ["concert-outbox-test", "concert-dlt-test"],
      },
      {
        id: "consumer",
        label: "Consumer",
        detail: "idempotent effect",
        x: 77,
        y: 56,
        width: 17,
        compact: { x: 8, y: 74, width: 84 },
        sourceIds: ["concert-dlt-test"],
        tone: "success",
      },
      {
        id: "dlt",
        label: "DLT",
        detail: "failure isolation",
        x: 55,
        y: 56,
        width: 17,
        compact: { x: 8, y: 90, width: 84 },
        sourceIds: ["concert-dlt-test"],
        tone: "danger",
      },
    ],
    edges: [
      {
        id: "transaction-outbox",
        from: "transaction",
        to: "outbox",
        label: "same commit",
        sourceIds: ["concert-outbox-test"],
      },
      {
        id: "outbox-relay",
        from: "outbox",
        to: "relay",
        label: "claim",
        sourceIds: ["concert-outbox-test"],
      },
      {
        id: "relay-kafka",
        from: "relay",
        to: "kafka",
        label: "publish",
        sourceIds: ["concert-outbox-test"],
      },
      {
        id: "kafka-consumer",
        from: "kafka",
        to: "consumer",
        label: "consume",
        sourceIds: ["concert-dlt-test"],
      },
      {
        id: "consumer-dlt",
        from: "consumer",
        to: "dlt",
        label: "fail",
        sourceIds: ["concert-dlt-test"],
      },
      {
        id: "dlt-kafka",
        from: "dlt",
        to: "kafka",
        label: "replay",
        sourceIds: ["concert-dlt-test"],
      },
    ],
    mobileSteps: [
      {
        text: "도메인 변경과 Outbox event를 같은 transaction에 기록합니다.",
        sourceIds: ["concert-outbox-test"],
      },
      {
        text: "relay가 발행 실패를 상태와 retry 시각으로 남깁니다.",
        sourceIds: ["concert-outbox-test"],
      },
      {
        text: "consumer 실패는 DLT로 격리한 뒤 원인을 확인하고 replay합니다.",
        sourceIds: ["concert-dlt-test"],
      },
    ],
  },
  {
    id: "realtime-message-lifecycle",
    title: "commit 뒤에만 상대에게 보이는 메시지",
    caption: "DB ID가 live delivery와 reconnect history를 연결합니다.",
    sourceIds: [
      "realtime-ordering-test",
      "realtime-lifecycle-refactor-commit",
      "realtime-client-state-test",
      "realtime-persistence-boundary-test",
      "realtime-redelivery-test",
      "realtime-persisted-ack-test",
      "realtime-lifecycle-e2e",
      "realtime-sync-api-test",
    ],
    nodes: [
      {
        id: "send",
        label: "SEND",
        detail: "clientMessageId",
        x: 4,
        y: 34,
        width: 16,
        compact: { x: 8, y: 10, width: 84 },
        sourceIds: ["realtime-client-state-test", "realtime-lifecycle-e2e"],
      },
      {
        id: "kafka",
        label: "Kafka",
        detail: "room partition",
        x: 26,
        y: 34,
        width: 17,
        compact: { x: 8, y: 26, width: 84 },
        sourceIds: [
          "realtime-ordering-test",
          "realtime-lifecycle-refactor-commit",
        ],
      },
      {
        id: "persist",
        label: "Persist",
        detail: "transaction",
        x: 49,
        y: 34,
        width: 17,
        compact: { x: 8, y: 42, width: 84 },
        sourceIds: [
          "realtime-lifecycle-refactor-commit",
          "realtime-persistence-boundary-test",
          "realtime-redelivery-test",
        ],
        tone: "accent",
      },
      {
        id: "db",
        label: "DB message",
        detail: "persisted ID",
        x: 67,
        y: 12,
        width: 16,
        compact: { x: 8, y: 58, width: 84 },
        sourceIds: [
          "realtime-persistence-boundary-test",
          "realtime-sync-api-test",
        ],
        tone: "success",
      },
      {
        id: "broadcast",
        label: "Broadcast",
        detail: "after commit",
        x: 67,
        y: 56,
        width: 16,
        compact: { x: 8, y: 74, width: 84 },
        sourceIds: [
          "realtime-persistence-boundary-test",
          "realtime-redelivery-test",
          "realtime-persisted-ack-test",
        ],
      },
      {
        id: "client",
        label: "Client merge",
        detail: "live + sync dedupe",
        x: 86,
        y: 34,
        width: 13,
        compact: { x: 8, y: 90, width: 84 },
        sourceIds: [
          "realtime-client-state-test",
          "realtime-persisted-ack-test",
          "realtime-lifecycle-e2e",
          "realtime-sync-api-test",
        ],
      },
    ],
    edges: [
      {
        id: "send-kafka",
        from: "send",
        to: "kafka",
        label: "accepted",
        sourceIds: ["realtime-client-state-test", "realtime-lifecycle-e2e"],
      },
      {
        id: "kafka-persist",
        from: "kafka",
        to: "persist",
        label: "consume",
        sourceIds: [
          "realtime-lifecycle-refactor-commit",
          "realtime-persistence-boundary-test",
        ],
      },
      {
        id: "persist-db",
        from: "persist",
        to: "db",
        label: "commit",
        sourceIds: ["realtime-persistence-boundary-test"],
      },
      {
        id: "db-broadcast",
        from: "db",
        to: "broadcast",
        label: "persisted payload",
        sourceIds: [
          "realtime-persistence-boundary-test",
          "realtime-persisted-ack-test",
        ],
      },
      {
        id: "broadcast-client",
        from: "broadcast",
        to: "client",
        label: "live",
        sourceIds: [
          "realtime-redelivery-test",
          "realtime-persisted-ack-test",
          "realtime-lifecycle-e2e",
        ],
      },
      {
        id: "db-client",
        from: "db",
        to: "client",
        label: "reconnect",
        sourceIds: ["realtime-sync-api-test", "realtime-lifecycle-e2e"],
      },
    ],
    mobileSteps: [
      {
        text: "clientMessageId로 임시 메시지를 추적합니다.",
        sourceIds: ["realtime-client-state-test"],
      },
      {
        text: "room partition에서 DB에 저장하고 message ID를 만듭니다.",
        sourceIds: [
          "realtime-ordering-test",
          "realtime-persistence-boundary-test",
        ],
      },
      {
        text: "commit된 payload만 broadcast하고 재연결에도 같은 ID를 사용합니다.",
        sourceIds: [
          "realtime-persistence-boundary-test",
          "realtime-persisted-ack-test",
          "realtime-sync-api-test",
        ],
      },
    ],
  },
  {
    id: "borrowme-return-and-harden",
    title: "현재 코드에 남긴 두 회귀 방지선",
    caption: "과거 개선 배수 대신 조회 SQL 상한과 재고 합계를 검증합니다.",
    sourceIds: ["borrow-query-guard", "borrow-stock-invariant"],
    nodes: [
      {
        id: "list",
        label: "Product list",
        detail: "DTO assembly",
        x: 4,
        y: 34,
        width: 19,
        compact: { x: 8, y: 10, width: 84 },
        sourceIds: ["borrow-query-guard"],
      },
      {
        id: "fetch",
        label: "Fetch path",
        detail: "product + owner + tags",
        x: 30,
        y: 12,
        width: 20,
        compact: { x: 8, y: 30, width: 84 },
        sourceIds: ["borrow-query-guard"],
        tone: "accent",
      },
      {
        id: "follow",
        label: "Bulk follow",
        detail: "candidate user IDs",
        x: 30,
        y: 56,
        width: 20,
        compact: { x: 8, y: 50, width: 84 },
        sourceIds: ["borrow-query-guard"],
      },
      {
        id: "query",
        label: "SQL guard",
        detail: "fixed upper bound",
        x: 58,
        y: 34,
        width: 18,
        compact: { x: 8, y: 70, width: 84 },
        sourceIds: ["borrow-query-guard"],
        tone: "success",
      },
      {
        id: "stock",
        label: "Stock guard",
        detail: "success + remaining",
        x: 82,
        y: 34,
        width: 16,
        compact: { x: 8, y: 90, width: 84 },
        sourceIds: ["borrow-stock-invariant"],
        tone: "success",
      },
    ],
    edges: [
      {
        id: "list-fetch",
        from: "list",
        to: "fetch",
        label: "load",
        sourceIds: ["borrow-query-guard"],
      },
      {
        id: "list-follow",
        from: "list",
        to: "follow",
        label: "bulk lookup",
        sourceIds: ["borrow-query-guard"],
      },
      {
        id: "fetch-query",
        from: "fetch",
        to: "query",
        label: "count",
        sourceIds: ["borrow-query-guard"],
      },
      {
        id: "follow-query",
        from: "follow",
        to: "query",
        label: "count",
        sourceIds: ["borrow-query-guard"],
      },
      {
        id: "query-stock",
        from: "query",
        to: "stock",
        label: "separate invariant",
        sourceIds: ["borrow-query-guard", "borrow-stock-invariant"],
      },
    ],
    mobileSteps: [
      {
        text: "상품·작성자·태그 fetch와 follow lookup을 나눕니다.",
        sourceIds: ["borrow-query-guard"],
      },
      {
        text: "Hibernate Statistics로 응답 조립까지의 SQL 상한을 확인합니다.",
        sourceIds: ["borrow-query-guard"],
      },
      {
        text: "동시 예약에서는 성공 수와 남은 재고의 합을 검증합니다.",
        sourceIds: ["borrow-stock-invariant"],
      },
    ],
  },
] satisfies readonly DiagramSpec[];

export const diagrams = diagramDrafts;

export function getDiagram(id: string) {
  return diagrams.find((diagram) => diagram.id === id);
}
