import type { VisualAsset } from "./types";

export const visualAssets: readonly VisualAsset[] = [
  {
    id: "memory-gallery",
    kind: "product-screen",
    src: "/work/memory/gallery.webp",
    alt: "Memory of Year의 시작, 로그인, 앨범 생성, 편지 화면을 나란히 배치한 실제 시연 화면 모음",
    caption: "시작부터 로그인·앨범·편지까지 이어지는 실제 팀 화면",
    transcript: [
      "사용자가 앱을 열고 회원가입과 로그인을 진행합니다.",
      "로그인 뒤 자신의 앨범을 만들고 내용을 꾸밉니다.",
      "앨범에 저장된 편지와 사진을 다시 엽니다.",
    ],
    sourceIds: ["memory-team-context", "memory-original-contribution"],
    width: 1440,
    height: 652,
  },
  {
    id: "memory-start",
    kind: "product-screen",
    src: "/work/memory/start.webp",
    alt: "Memory of Year 앱의 시작 화면",
    caption: "시작 화면",
    transcript: ["Memory of Year 앱을 여는 시작 화면입니다."],
    sourceIds: ["memory-team-context"],
    width: 360,
    height: 650,
  },
  {
    id: "memory-auth",
    kind: "product-screen",
    src: "/work/memory/auth.webp",
    alt: "Memory of Year 회원가입과 로그인 화면",
    caption: "회원가입과 로그인",
    transcript: ["사용자가 회원가입한 뒤 로그인하는 실제 팀 화면입니다."],
    sourceIds: ["memory-original-contribution", "memory-team-context"],
    width: 360,
    height: 652,
  },
  {
    id: "memory-album",
    kind: "product-screen",
    src: "/work/memory/album.webp",
    alt: "Memory of Year 앨범을 만들고 꾸미는 화면",
    caption: "앨범 생성과 꾸미기",
    transcript: ["자신의 앨범을 만들고 색과 내용을 꾸미는 실제 팀 화면입니다."],
    sourceIds: ["memory-original-contribution", "memory-team-context"],
    width: 360,
    height: 652,
  },
  {
    id: "memory-letter",
    kind: "product-screen",
    src: "/work/memory/letter.webp",
    alt: "Memory of Year 앨범에서 편지와 사진을 여는 화면",
    caption: "편지와 사진 열기",
    transcript: ["앨범에 저장된 편지와 사진을 다시 여는 실제 팀 화면입니다."],
    sourceIds: ["memory-original-contribution", "memory-team-context"],
    width: 360,
    height: 650,
  },
  {
    id: "memory-deployment-map",
    kind: "deployment-map",
    src: "/work/diagrams/memory-deployment-boundary.png",
    alt: "브라우저가 HTTPS로 EC2의 Spring API를 호출하고 API가 데이터베이스와 S3를 사용하는 배포 경계",
    caption: "당시 직접 구성한 브라우저·HTTPS·EC2 API·DB·S3 배포 경계",
    transcript: [
      "프론트엔드는 HTTPS로 EC2의 Spring API를 호출했습니다.",
      "인증과 앨범·편지 데이터는 배포 데이터베이스에 저장했습니다.",
      "사진 파일은 S3에 저장하고 API가 접근할 URL을 돌려줬습니다.",
      "팀 시연은 이 배포 API를 연결한 실제 화면으로 진행했습니다.",
    ],
    sourceIds: ["memory-deployment-context"],
    width: 2002,
    height: 835,
  },
  {
    id: "concert-seat-client",
    kind: "product-screen",
    src: "/work/concert-seat-selection.webp",
    alt: "Concert Booking 클라이언트에서 좌석과 남은 예약 시간을 확인하는 화면",
    caption: "대기열 뒤 좌석 선택과 예약 복구를 재현한 실제 클라이언트",
    transcript: [
      "좌석 상태, 선택한 좌석, 예약 만료 시간과 다음 행동을 한 화면에서 확인합니다.",
      "동일 좌석 경합에서 실패한 사용자는 갱신된 좌석표에서 다른 좌석을 선택합니다.",
    ],
    sourceIds: [
      "concert-product-rebuild-commit",
      "concert-product-journey-e2e",
    ],
    width: 1440,
    height: 1000,
  },
  {
    id: "realtime-client",
    kind: "product-screen",
    src: "/work/realtime-conversation.webp",
    alt: "Realtime Chat 클라이언트에서 Alice와 Bob이 메시지 저장 상태를 확인하는 화면",
    caption: "두 사용자와 두 app node로 검증한 실제 채팅 클라이언트",
    transcript: [
      "발신자는 메시지의 보내는 중, 큐 접수, 저장 완료 상태를 구분합니다.",
      "오프라인 사용자는 재연결 뒤 마지막 저장 메시지 이후를 보충합니다.",
    ],
    sourceIds: ["realtime-product-rebuild-commit", "realtime-lifecycle-e2e"],
    width: 1440,
    height: 900,
  },
  {
    id: "borrow-lifecycle-map",
    kind: "decision-map",
    src: "/work/diagrams/borrow-reservation-lifecycle.png",
    alt: "예약자와 상품 소유자가 대여 요청, 승인, 인도, 반납 또는 취소를 처리하고 재고를 복원하는 상태 흐름",
    caption: "역할과 상태, 재고 복원을 한 경계에서 처리하는 대여 생명주기",
    transcript: [
      "예약자가 요청하면 REQUESTED 상태가 되고 재고를 hold합니다.",
      "상품 소유자가 승인하면 APPROVED, 인도를 확인하면 BORROWED가 됩니다.",
      "반납 확인은 RETURNED로 바꾸고 hold한 재고를 한 번 복원합니다.",
      "거절과 인도 전 취소도 재고를 한 번 복원합니다.",
      "각 변화는 역할을 확인한 뒤 transition과 알림을 한 번 기록합니다.",
    ],
    sourceIds: ["borrow-lifecycle-proof"],
    width: 2508,
    height: 1304,
  },
  {
    id: "concert-seat-recovery-map",
    kind: "decision-map",
    src: "/work/diagrams/concert-seat-loser-recovery.png",
    alt: "두 사용자가 같은 좌석을 요청했을 때 한 명만 예약하고 패자는 최신 좌석표에서 다른 좌석을 선택하는 흐름",
    caption: "동일 좌석의 승자 결정과 패자의 예매 복구",
    transcript: [
      "두 브라우저가 같은 입장 상태에서 같은 좌석을 선택합니다.",
      "두 요청은 예약 경계에 거의 동시에 도착합니다.",
      "좌석 row와 고유 제약으로 한 사용자만 예약합니다.",
      "패자에게 충돌 응답을 돌려주고 Queue Token은 유지합니다.",
      "클라이언트는 최신 좌석표를 다시 받습니다.",
      "패자는 다른 좌석을 골라 예매를 계속합니다.",
    ],
    sourceIds: ["concert-seat-contention-test", "concert-product-journey-e2e"],
    width: 3061,
    height: 981,
  },
  {
    id: "concert-event-recovery-map",
    kind: "decision-map",
    src: "/work/diagrams/concert-event-recovery.png",
    alt: "예약 이벤트를 Outbox에 기록하고 발행 실패를 재시도·DEAD·DLT로 격리한 뒤 replay하는 흐름",
    caption: "Outbox 실패부터 DLT replay까지의 이벤트 복구 경계",
    transcript: [
      "예약과 Outbox 이벤트를 같은 데이터베이스 트랜잭션에 저장합니다.",
      "relay 발행이 실패하면 횟수와 다음 시각을 남겨 재시도합니다.",
      "최대 횟수를 넘은 Outbox는 DEAD로 격리합니다.",
      "consumer 실패 이벤트는 DLT에서 별도로 보관합니다.",
      "관리 replay는 한 번에 제한된 이벤트만 다시 보냅니다.",
      "consumer는 이미 처리한 좌석 반환을 중복 적용하지 않습니다.",
    ],
    sourceIds: ["concert-outbox-test", "concert-dlt-test"],
    width: 3061,
    height: 861,
  },
  {
    id: "realtime-persist-map",
    kind: "decision-map",
    src: "/work/diagrams/realtime-persist-before-broadcast.png",
    alt: "저장과 broadcast가 독립적으로 실행되던 구조와 DB commit 뒤에만 broadcast하는 구조 비교",
    caption: "상대 화면보다 DB 저장을 먼저 끝내도록 바꾼 메시지 경계",
    transcript: [
      "기존 구조에서는 persistence와 broadcast consumer가 독립적으로 실행됐습니다.",
      "broadcast가 먼저 끝나면 DB에 없는 메시지가 상대 화면에 보일 수 있었습니다.",
      "새 구조는 한 consumer가 DB commit을 먼저 끝냅니다.",
      "저장된 DB ID를 포함한 메시지만 Redis와 발신자에게 전달하고 성공 뒤 Kafka ACK를 보냅니다.",
    ],
    sourceIds: [
      "realtime-product-rebuild-commit",
      "realtime-persistence-boundary-test",
      "realtime-redelivery-test",
    ],
    width: 2701,
    height: 1242,
  },
];

export function getVisual(id: string) {
  return visualAssets.find((visual) => visual.id === id);
}

export function getVisuals(ids: readonly string[]) {
  return ids.flatMap((id) => {
    const visual = getVisual(id);
    return visual ? [visual] : [];
  });
}
