import type { DiagramSpec } from "../types.ts";

export const billingIdempotencyWebhookLedgerSpec = {
  slug: "billing-idempotency-webhook-ledger",
  outputFile:
    "public/architecture/cases/billing-idempotency-webhook-ledger.svg",
  sourceFile: "src/architecture/specs/billing-idempotency-webhook-ledger.ts",
  title: "과금 idempotency / webhook / ledger: 문제 구간 아키텍처",
  description:
    "Tenant billing flow with API key hash, usage idempotency, invoice, webhook duplicate conflict, append-only ledger, audit log.",
  width: 1100,
  height: 620,
  containers: [
    {
      id: "usage",
      title: "Gateway / Usage flow",
      x: 30,
      y: 120,
      w: 1040,
      h: 230,
    },
    {
      id: "billing",
      title: "Billing / Audit flow",
      x: 30,
      y: 390,
      w: 1040,
      h: 160,
    },
  ],
  nodes: [
    {
      id: "tenant",
      x: 40,
      y: 220,
      w: 140,
      h: 80,
      title: "Tenant",
      lines: ["usage 요청"],
      kind: "external",
    },
    {
      id: "apiKey",
      x: 220,
      y: 220,
      w: 160,
      h: 80,
      title: "API Key",
      lines: ["prefix/hash", "원문 미저장"],
      kind: "transaction",
    },
    {
      id: "usageGateway",
      x: 420,
      y: 220,
      w: 160,
      h: 80,
      title: "Usage Gateway",
      lines: ["retry idempotency"],
      kind: "service",
    },
    {
      id: "redis",
      x: 420,
      y: 120,
      w: 160,
      h: 80,
      title: "Redis",
      lines: ["rate limit"],
      kind: "cache",
    },
    {
      id: "invoice",
      x: 620,
      y: 120,
      w: 160,
      h: 80,
      title: "Invoice",
      lines: ["tenant 집계"],
      kind: "service",
    },
    {
      id: "usageEvent",
      x: 620,
      y: 220,
      w: 160,
      h: 80,
      title: "Usage Event",
      lines: ["idempotency"],
      kind: "transaction",
    },
    {
      id: "postgres",
      x: 840,
      y: 220,
      w: 200,
      h: 100,
      title: "PostgreSQL",
      lines: ["Usage / Invoice", "Ledger / Audit"],
      kind: "database",
    },
    {
      id: "provider",
      x: 40,
      y: 420,
      w: 160,
      h: 80,
      title: "Payment Mock",
      lines: ["webhook delivery"],
      kind: "external",
    },
    {
      id: "webhook",
      x: 240,
      y: 420,
      w: 160,
      h: 80,
      title: "Webhook",
      lines: ["duplicate/conflict"],
      kind: "failure",
    },
    {
      id: "ledger",
      x: 460,
      y: 420,
      w: 160,
      h: 80,
      title: "Ledger Entry",
      lines: ["append-only"],
      kind: "ledger",
    },
    {
      id: "sanitizer",
      x: 660,
      y: 420,
      w: 160,
      h: 80,
      title: "Audit Sanitizer",
      lines: ["metadata redaction"],
      kind: "service",
    },
    {
      id: "audit",
      x: 860,
      y: 420,
      w: 160,
      h: 80,
      title: "Audit Log",
      lines: ["민감값 제거"],
      kind: "database",
    },
  ],
  edges: [
    {
      id: "tenant-to-api-key",
      from: "tenant",
      to: "apiKey",
      fromPort: "right",
      toPort: "left",
      label: "X-API-Key",
      kind: "sync",
      labelPosition: { x: 200, y: 190 },
    },
    {
      id: "api-key-to-gateway",
      from: "apiKey",
      to: "usageGateway",
      fromPort: "right",
      toPort: "left",
      label: "hash 검증",
      kind: "sync",
      labelPosition: { x: 400, y: 330 },
    },
    {
      id: "gateway-to-usage-event",
      from: "usageGateway",
      to: "usageEvent",
      fromPort: "right",
      toPort: "left",
      label: "사용량 기록",
      kind: "sync",
      labelPosition: { x: 600, y: 330 },
    },
    {
      id: "gateway-to-redis",
      from: "usageGateway",
      to: "redis",
      fromPort: "top",
      toPort: "bottom",
      label: "rate limit",
      kind: "sync",
      labelPosition: { x: 520, y: 90 },
    },
    {
      id: "usage-event-to-invoice",
      from: "usageEvent",
      to: "invoice",
      fromPort: "top",
      toPort: "bottom",
      label: "invoice 집계",
      kind: "async",
      labelPosition: { x: 700, y: 90 },
    },
    {
      id: "invoice-to-postgres",
      from: "invoice",
      to: "postgres",
      fromPort: "right",
      toPort: "top",
      via: [
        { x: 800, y: 160 },
        { x: 940, y: 160 },
      ],
      label: "정산 기준 저장",
      kind: "sync",
      labelPosition: { x: 850, y: 180 },
    },
    {
      id: "usage-to-postgres",
      from: "usageEvent",
      to: "postgres",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 800, y: 260 },
        { x: 800, y: 270 },
      ],
      label: "최종 기준 데이터",
      kind: "sync",
      labelPosition: { x: 810, y: 350 },
    },
    {
      id: "provider-to-webhook",
      from: "provider",
      to: "webhook",
      fromPort: "right",
      toPort: "left",
      label: "signature 검증",
      kind: "async",
      labelPosition: { x: 220, y: 390 },
    },
    {
      id: "webhook-to-ledger",
      from: "webhook",
      to: "ledger",
      fromPort: "right",
      toPort: "left",
      label: "중복 처리",
      kind: "failure",
      labelPosition: { x: 430, y: 390 },
    },
    {
      id: "ledger-to-sanitizer",
      from: "ledger",
      to: "sanitizer",
      fromPort: "right",
      toPort: "left",
      label: "감사 메타데이터",
      kind: "sync",
      labelPosition: { x: 640, y: 390 },
    },
    {
      id: "sanitizer-to-audit",
      from: "sanitizer",
      to: "audit",
      fromPort: "right",
      toPort: "left",
      label: "redaction",
      kind: "sync",
      labelPosition: { x: 840, y: 390 },
    },
    {
      id: "audit-to-postgres",
      from: "audit",
      to: "postgres",
      fromPort: "top",
      toPort: "bottom",
      label: "append audit",
      kind: "sync",
      labelPosition: { x: 940, y: 380 },
    },
  ],
} satisfies DiagramSpec;
