import type { DiagramSpec } from "../types.ts";

export const borrowmeProductListNPlusOneSpec = {
  slug: "borrowme-product-list-n-plus-one",
  outputFile: "public/architecture/cases/borrowme-product-list-n-plus-one.svg",
  sourceFile: "src/architecture/specs/borrowme-product-list-n-plus-one.ts",
  title: "BorrowMe 상품 목록 N+1: 문제 구간 아키텍처",
  description:
    "Before and after architecture for BorrowMe product list N+1 query reduction and current query-count guard.",
  width: 1040,
  height: 560,
  containers: [
    {
      id: "request",
      title: "Product list read path",
      x: 40,
      y: 120,
      w: 380,
      h: 260,
    },
    { id: "compare", title: "Before / After", x: 440, y: 80, w: 260, h: 420 },
    {
      id: "data",
      title: "Data / claim boundary",
      x: 740,
      y: 120,
      w: 260,
      h: 360,
    },
  ],
  nodes: [
    {
      id: "client",
      x: 60,
      y: 220,
      w: 140,
      h: 80,
      title: "Client",
      lines: ["상품 목록"],
      kind: "external",
    },
    {
      id: "productApi",
      x: 240,
      y: 220,
      w: 160,
      h: 80,
      title: "Product API",
      lines: ["첫 화면 조회"],
      kind: "service",
    },
    {
      id: "before",
      x: 460,
      y: 120,
      w: 220,
      h: 120,
      title: "Before",
      lines: ["원본 기록 201 queries", "p95 1,010ms 기록"],
      kind: "failure",
    },
    {
      id: "after",
      x: 460,
      y: 340,
      w: 220,
      h: 120,
      title: "After",
      lines: ["현재 guard 3 queries 이하", "local snapshot 별도 표기"],
      kind: "database",
    },
    {
      id: "mysql",
      x: 760,
      y: 220,
      w: 180,
      h: 100,
      title: "MySQL",
      lines: ["Product / Image", "Reservation"],
      kind: "database",
    },
    {
      id: "claimBoundary",
      x: 760,
      y: 380,
      w: 200,
      h: 80,
      title: "Claim boundary",
      lines: ["원본 README와", "현재 검증 분리"],
      kind: "note",
    },
  ],
  edges: [
    {
      id: "client-to-api",
      from: "client",
      to: "productApi",
      fromPort: "right",
      toPort: "left",
      label: "목록 조회",
      kind: "sync",
      labelPosition: { x: 220, y: 190 },
    },
    {
      id: "api-to-before",
      from: "productApi",
      to: "before",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 430, y: 260 },
        { x: 430, y: 180 },
      ],
      label: "반복 조회",
      kind: "failure",
      labelPosition: { x: 430, y: 90 },
    },
    {
      id: "api-to-after",
      from: "productApi",
      to: "after",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 430, y: 260 },
        { x: 430, y: 400 },
      ],
      label: "조회 경로 재구성",
      kind: "sync",
      labelPosition: { x: 430, y: 500 },
    },
    {
      id: "before-to-mysql",
      from: "before",
      to: "mysql",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 720, y: 180 },
        { x: 720, y: 270 },
      ],
      label: "201 queries",
      kind: "failure",
      labelPosition: { x: 720, y: 90 },
    },
    {
      id: "after-to-mysql",
      from: "after",
      to: "mysql",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 720, y: 400 },
        { x: 720, y: 270 },
      ],
      label: "3 queries 이하",
      kind: "sync",
      labelPosition: { x: 700, y: 500 },
    },
    {
      id: "after-to-claim",
      from: "after",
      to: "claimBoundary",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 720, y: 400 },
        { x: 720, y: 420 },
      ],
      label: "claim 분리",
      kind: "sync",
      labelPosition: { x: 820, y: 500 },
    },
  ],
} satisfies DiagramSpec;
