import type { DiagramSpec } from "../types.ts";

export const borrowmeProductListNPlusOneSpec = {
  slug: "borrowme-product-list-n-plus-one",
  outputFile: "public/architecture/cases/borrowme-product-list-n-plus-one.svg",
  sourceFile: "src/architecture/specs/borrowme-product-list-n-plus-one.ts",
  title: "BorrowMe 상품 목록: 조회 경로와 현재 검증",
  description:
    "Current product list fetch, bulk follow lookup, MySQL query-count guards, and local snapshot evidence.",
  width: 1040,
  height: 560,
  containers: [
    {
      id: "request",
      title: "Product list read path",
      x: 40,
      y: 120,
      w: 380,
      h: 260,
    },
    {
      id: "query",
      title: "Bounded query paths",
      x: 440,
      y: 80,
      w: 260,
      h: 420,
    },
    {
      id: "data",
      title: "Data / evidence boundary",
      x: 740,
      y: 120,
      w: 260,
      h: 360,
    },
  ],
  nodes: [
    {
      id: "client",
      x: 60,
      y: 220,
      w: 140,
      h: 80,
      title: "Client",
      lines: ["상품 목록"],
      kind: "external",
    },
    {
      id: "productApi",
      x: 240,
      y: 220,
      w: 160,
      h: 80,
      title: "Product API",
      lines: ["첫 화면 조회"],
      kind: "service",
    },
    {
      id: "fetchPath",
      x: 460,
      y: 120,
      w: 220,
      h: 120,
      title: "Product Fetch Path",
      lines: ["상품 / 작성자 / 태그", "fetch SQL 1회 guard"],
      kind: "service",
    },
    {
      id: "followLookup",
      x: 460,
      y: 340,
      w: 220,
      h: 120,
      title: "Bulk Follow Lookup",
      lines: ["작성자 ID 일괄 조회", "인증 API SQL 5회 이하"],
      kind: "service",
    },
    {
      id: "mysql",
      x: 760,
      y: 220,
      w: 180,
      h: 100,
      title: "MySQL",
      lines: ["Product / Image", "Reservation"],
      kind: "database",
    },
    {
      id: "currentEvidence",
      x: 760,
      y: 380,
      w: 200,
      h: 80,
      title: "Current Snapshot",
      lines: ["p95 358.1088ms", "HTTP failure 0"],
      kind: "note",
    },
  ],
  edges: [
    {
      id: "client-to-api",
      from: "client",
      to: "productApi",
      fromPort: "right",
      toPort: "left",
      label: "목록 조회",
      kind: "sync",
      labelPosition: { x: 220, y: 190 },
    },
    {
      id: "api-to-fetch",
      from: "productApi",
      to: "fetchPath",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 440, y: 260 },
        { x: 440, y: 180 },
      ],
      label: "연관 데이터 조회",
      kind: "sync",
      labelPosition: { x: 470, y: 260 },
    },
    {
      id: "api-to-follow",
      from: "productApi",
      to: "followLookup",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 440, y: 260 },
        { x: 440, y: 400 },
      ],
      label: "작성자 ID 일괄 조회",
      kind: "sync",
      labelPosition: { x: 430, y: 500 },
    },
    {
      id: "fetch-to-mysql",
      from: "fetchPath",
      to: "mysql",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 720, y: 180 },
        { x: 720, y: 270 },
      ],
      label: "fetch join",
      kind: "sync",
      labelPosition: { x: 720, y: 90 },
    },
    {
      id: "follow-to-mysql",
      from: "followLookup",
      to: "mysql",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 720, y: 400 },
        { x: 720, y: 270 },
      ],
      label: "bulk lookup",
      kind: "sync",
      labelPosition: { x: 700, y: 500 },
    },
    {
      id: "api-to-evidence",
      from: "productApi",
      to: "currentEvidence",
      fromPort: "bottom",
      toPort: "left",
      via: [
        { x: 320, y: 500 },
        { x: 720, y: 500 },
        { x: 720, y: 420 },
      ],
      label: "현재 조건만 기록",
      kind: "sync",
      labelPosition: { x: 520, y: 520 },
    },
  ],
} satisfies DiagramSpec;
