import type { DiagramSpec } from "../types.ts";

export const chatRoomNPlusOneRpsSpec = {
  slug: "chat-room-n-plus-one-rps",
  outputFile: "public/architecture/cases/chat-room-n-plus-one-rps.svg",
  sourceFile: "src/architecture/specs/chat-room-n-plus-one-rps.ts",
  title: "채팅방 조회 API N+1: 문제 구간 아키텍처",
  description:
    "Before and after architecture for chat room list API N+1 query removal.",
  width: 1040,
  height: 560,
  containers: [
    { id: "request", title: "Read path", x: 40, y: 120, w: 380, h: 260 },
    { id: "compare", title: "Before / After", x: 440, y: 80, w: 260, h: 420 },
    { id: "data", title: "Data boundary", x: 740, y: 120, w: 260, h: 360 },
  ],
  nodes: [
    {
      id: "client",
      x: 60,
      y: 220,
      w: 140,
      h: 80,
      title: "Client",
      lines: ["방 목록 조회"],
      kind: "external",
    },
    {
      id: "api",
      x: 240,
      y: 220,
      w: 160,
      h: 80,
      title: "Chat Room API",
      lines: ["목록 응답"],
      kind: "service",
    },
    {
      id: "before",
      x: 460,
      y: 120,
      w: 220,
      h: 120,
      title: "Before",
      lines: ["2N+1 queries", "RPS 937", "p95 212.85ms"],
      kind: "failure",
    },
    {
      id: "after",
      x: 460,
      y: 340,
      w: 220,
      h: 120,
      title: "After",
      lines: ["1 query", "RPS 1,598", "p95 149.22ms"],
      kind: "database",
    },
    {
      id: "messageDb",
      x: 760,
      y: 220,
      w: 180,
      h: 100,
      title: "Message DB",
      lines: ["Room", "Participant"],
      kind: "database",
    },
    {
      id: "delivery",
      x: 760,
      y: 380,
      w: 180,
      h: 80,
      title: "Delivery",
      lines: ["production/mixed 예정"],
      kind: "note",
    },
  ],
  edges: [
    {
      id: "client-to-api",
      from: "client",
      to: "api",
      fromPort: "right",
      toPort: "left",
      label: "조회 요청",
      kind: "sync",
      labelPosition: { x: 220, y: 190 },
    },
    {
      id: "api-to-before",
      from: "api",
      to: "before",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 440, y: 260 },
        { x: 440, y: 180 },
      ],
      label: "기존 반복 조회",
      kind: "failure",
      labelPosition: { x: 470, y: 260 },
    },
    {
      id: "api-to-after",
      from: "api",
      to: "after",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 440, y: 260 },
        { x: 440, y: 400 },
      ],
      label: "조회 경로 재구성",
      kind: "sync",
      labelPosition: { x: 430, y: 500 },
    },
    {
      id: "before-to-db",
      from: "before",
      to: "messageDb",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 720, y: 180 },
        { x: 720, y: 270 },
      ],
      label: "2N+1",
      kind: "failure",
      labelPosition: { x: 720, y: 90 },
    },
    {
      id: "after-to-db",
      from: "after",
      to: "messageDb",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 720, y: 400 },
        { x: 720, y: 270 },
      ],
      label: "1 query",
      kind: "sync",
      labelPosition: { x: 700, y: 500 },
    },
    {
      id: "after-to-delivery",
      from: "after",
      to: "delivery",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 720, y: 400 },
        { x: 720, y: 420 },
      ],
      label: "전달 지표 분리",
      kind: "async",
      labelPosition: { x: 820, y: 500 },
    },
  ],
} satisfies DiagramSpec;
