import type { DiagramSpec } from "../types.ts";

export const concertSeatOversellingConsistencySpec = {
  slug: "concert-seat-overselling-consistency",
  outputFile:
    "public/architecture/cases/concert-seat-overselling-consistency.svg",
  sourceFile: "src/architecture/specs/concert-seat-overselling-consistency.ts",
  title: "동일 좌석 예매 경합: 문제 구간 아키텍처",
  description:
    "Queue token, reservation transaction, Outbox, Kafka, DLT, PostgreSQL reconciliation flow for same-seat contention.",
  width: 1040,
  height: 560,
  containers: [
    { id: "entry", title: "Entry boundary", x: 40, y: 90, w: 360, h: 220 },
    {
      id: "event",
      title: "Transaction / Event boundary",
      x: 420,
      y: 90,
      w: 580,
      h: 220,
    },
    {
      id: "recovery",
      title: "Recovery boundary",
      x: 40,
      y: 340,
      w: 960,
      h: 150,
    },
  ],
  nodes: [
    {
      id: "client",
      x: 60,
      y: 180,
      w: 140,
      h: 80,
      title: "Client",
      lines: ["동일 좌석 요청"],
      kind: "external",
    },
    {
      id: "queue",
      x: 240,
      y: 180,
      w: 160,
      h: 80,
      title: "Queue Token",
      lines: ["우회 제한"],
      kind: "cache",
    },
    {
      id: "reservation",
      x: 440,
      y: 140,
      w: 220,
      h: 140,
      title: "Reservation Tx",
      lines: [
        "Idempotency-Key",
        "Seat lock",
        "Reservation insert",
        "Outbox insert",
      ],
      kind: "transaction",
    },
    {
      id: "outbox",
      x: 700,
      y: 140,
      w: 160,
      h: 100,
      title: "Outbox Table",
      lines: ["이벤트 의도 저장", "commit 이후 relay"],
      kind: "transaction",
    },
    {
      id: "kafka",
      x: 900,
      y: 180,
      w: 100,
      h: 80,
      title: "Kafka",
      lines: ["비동기 발행"],
      kind: "broker",
    },
    {
      id: "dlt",
      x: 900,
      y: 360,
      w: 100,
      h: 80,
      title: "DLT",
      lines: ["실패 격리"],
      kind: "failure",
    },
    {
      id: "postgres",
      x: 440,
      y: 380,
      w: 220,
      h: 80,
      title: "PostgreSQL",
      lines: ["좌석/예약 최종 기준 데이터"],
      kind: "database",
    },
    {
      id: "reconcile",
      x: 700,
      y: 380,
      w: 200,
      h: 80,
      title: "Redis Reconcile",
      lines: ["보조 상태 복구"],
      kind: "failure",
    },
  ],
  edges: [
    {
      id: "client-to-queue",
      from: "client",
      to: "queue",
      fromPort: "right",
      toPort: "left",
      label: "대기열 토큰 검증",
      kind: "sync",
      labelPosition: { x: 220, y: 150 },
    },
    {
      id: "queue-to-reservation",
      from: "queue",
      to: "reservation",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 420, y: 220 },
        { x: 420, y: 210 },
      ],
      label: "예약 요청",
      kind: "sync",
      labelPosition: { x: 420, y: 300 },
    },
    {
      id: "reservation-to-outbox",
      from: "reservation",
      to: "outbox",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 680, y: 210 },
        { x: 680, y: 190 },
      ],
      label: "이벤트 의도 저장",
      kind: "sync",
      labelPosition: { x: 680, y: 110 },
    },
    {
      id: "outbox-to-kafka",
      from: "outbox",
      to: "kafka",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 880, y: 190 },
        { x: 880, y: 220 },
      ],
      label: "commit 이후 발행",
      kind: "async",
      labelPosition: { x: 880, y: 120 },
    },
    {
      id: "kafka-to-dlt",
      from: "kafka",
      to: "dlt",
      fromPort: "bottom",
      toPort: "top",
      label: "consumer 실패",
      kind: "failure",
      labelPosition: { x: 960, y: 310 },
    },
    {
      id: "reservation-to-postgres",
      from: "reservation",
      to: "postgres",
      fromPort: "bottom",
      toPort: "top",
      label: "DB commit",
      kind: "sync",
      labelPosition: { x: 530, y: 330 },
    },
    {
      id: "kafka-to-reconcile",
      from: "kafka",
      to: "reconcile",
      fromPort: "bottom",
      toPort: "top",
      via: [
        { x: 950, y: 320 },
        { x: 800, y: 320 },
      ],
      label: "Redis 불일치 감지",
      kind: "failure",
      labelPosition: { x: 800, y: 320 },
    },
    {
      id: "postgres-to-reconcile",
      from: "postgres",
      to: "reconcile",
      fromPort: "right",
      toPort: "left",
      label: "PostgreSQL 기준 복구",
      kind: "replay",
      labelPosition: { x: 680, y: 340 },
    },
  ],
} satisfies DiagramSpec;
