import type { DiagramSpec } from "../types.ts";

export const concertOutboxDltRecoverySpec = {
  slug: "concert-outbox-dlt-recovery",
  outputFile: "public/architecture/cases/concert-outbox-dlt-recovery.svg",
  sourceFile: "src/architecture/specs/concert-outbox-dlt-recovery.ts",
  title: "Outbox / DLT 복구: 문제 구간 아키텍처",
  description:
    "Outbox relay, Kafka, consumer, DLT, DEAD, manual replay, and PostgreSQL recovery path.",
  width: 1040,
  height: 560,
  containers: [
    { id: "commit", title: "Commit boundary", x: 40, y: 110, w: 420, h: 190 },
    {
      id: "publish",
      title: "Publish / consume boundary",
      x: 480,
      y: 110,
      w: 520,
      h: 190,
    },
    {
      id: "recovery",
      title: "Failure recovery",
      x: 40,
      y: 340,
      w: 960,
      h: 150,
    },
  ],
  nodes: [
    {
      id: "domainTx",
      x: 60,
      y: 180,
      w: 180,
      h: 100,
      title: "Domain Tx",
      lines: ["상태 변경", "Outbox insert"],
      kind: "transaction",
    },
    {
      id: "outbox",
      x: 280,
      y: 180,
      w: 160,
      h: 100,
      title: "Outbox",
      lines: ["PENDING", "RETRYING / DEAD"],
      kind: "database",
    },
    {
      id: "relay",
      x: 480,
      y: 180,
      w: 140,
      h: 100,
      title: "Relay",
      lines: ["재시도 발행"],
      kind: "worker",
    },
    {
      id: "kafka",
      x: 660,
      y: 180,
      w: 120,
      h: 100,
      title: "Kafka",
      lines: ["event"],
      kind: "broker",
    },
    {
      id: "consumer",
      x: 820,
      y: 180,
      w: 160,
      h: 100,
      title: "Consumer",
      lines: ["idempotency"],
      kind: "service",
    },
    {
      id: "dlt",
      x: 660,
      y: 380,
      w: 120,
      h: 80,
      title: "DLT",
      lines: ["실패 격리"],
      kind: "failure",
    },
    {
      id: "manualReplay",
      x: 460,
      y: 380,
      w: 160,
      h: 80,
      title: "Manual Replay",
      lines: ["확인 후 재처리"],
      kind: "failure",
    },
    {
      id: "domainDb",
      x: 80,
      y: 380,
      w: 200,
      h: 80,
      title: "Domain DB",
      lines: ["예약/결제 기준 데이터"],
      kind: "database",
    },
  ],
  edges: [
    {
      id: "domain-to-outbox",
      from: "domainTx",
      to: "outbox",
      fromPort: "right",
      toPort: "left",
      label: "같은 transaction",
      kind: "sync",
      labelPosition: { x: 260, y: 150 },
    },
    {
      id: "outbox-to-relay",
      from: "outbox",
      to: "relay",
      fromPort: "right",
      toPort: "left",
      label: "PENDING 조회",
      kind: "sync",
      labelPosition: { x: 460, y: 150 },
    },
    {
      id: "relay-to-kafka",
      from: "relay",
      to: "kafka",
      fromPort: "right",
      toPort: "left",
      label: "발행",
      kind: "async",
      labelPosition: { x: 640, y: 150 },
    },
    {
      id: "kafka-to-consumer",
      from: "kafka",
      to: "consumer",
      fromPort: "right",
      toPort: "left",
      label: "consume",
      kind: "async",
      labelPosition: { x: 800, y: 150 },
    },
    {
      id: "consumer-to-dlt",
      from: "consumer",
      to: "dlt",
      fromPort: "bottom",
      toPort: "top",
      via: [
        { x: 900, y: 330 },
        { x: 720, y: 330 },
      ],
      label: "처리 실패",
      kind: "failure",
      labelPosition: { x: 820, y: 330 },
    },
    {
      id: "dlt-to-manual",
      from: "dlt",
      to: "manualReplay",
      fromPort: "left",
      toPort: "right",
      label: "DEAD 확인",
      kind: "failure",
      labelPosition: { x: 640, y: 350 },
    },
    {
      id: "manual-to-outbox",
      from: "manualReplay",
      to: "outbox",
      fromPort: "left",
      toPort: "bottom",
      via: [{ x: 360, y: 420 }],
      label: "수동 재처리",
      kind: "replay",
      labelPosition: { x: 360, y: 420 },
    },
    {
      id: "domain-to-db",
      from: "domainTx",
      to: "domainDb",
      fromPort: "bottom",
      toPort: "top",
      via: [
        { x: 150, y: 330 },
        { x: 180, y: 330 },
      ],
      label: "도메인 상태 저장",
      kind: "sync",
      labelPosition: { x: 180, y: 330 },
    },
  ],
} satisfies DiagramSpec;
