import type { DiagramSpec } from "../types.ts";

export const realtimeDeliveryConsistencySpec = {
  slug: "realtime-delivery-consistency",
  outputFile: "public/architecture/cases/realtime-delivery-consistency.svg",
  sourceFile: "src/architecture/specs/realtime-delivery-consistency.ts",
  title: "Realtime delivery consistency: 검증 경계",
  description:
    "STOMP subscription authorization, room-keyed Kafka ordering, persistence and fan-out, receiver evidence, and reconnect sync boundaries.",
  width: 1120,
  height: 680,
  containers: [
    {
      id: "entry",
      title: "Connection / authorization",
      x: 20,
      y: 80,
      w: 380,
      h: 360,
    },
    {
      id: "delivery",
      title: "Room delivery",
      x: 420,
      y: 80,
      w: 680,
      h: 360,
    },
    {
      id: "recovery",
      title: "Reconnect / evidence",
      x: 20,
      y: 460,
      w: 1080,
      h: 140,
    },
  ],
  nodes: [
    {
      id: "client",
      x: 40,
      y: 200,
      w: 140,
      h: 80,
      title: "STOMP Client",
      lines: ["CONNECT / SEND"],
      kind: "external",
    },
    {
      id: "subscription",
      x: 220,
      y: 120,
      w: 160,
      h: 100,
      title: "SUBSCRIBE Auth",
      lines: ["멤버십 검사", "비멤버 거부"],
      kind: "gateway",
    },
    {
      id: "messageApi",
      x: 220,
      y: 300,
      w: 160,
      h: 100,
      title: "Message Input",
      lines: ["clientMessageId", "roomId를 key로"],
      kind: "service",
    },
    {
      id: "kafka",
      x: 460,
      y: 300,
      w: 140,
      h: 100,
      title: "Kafka",
      lines: ["room partition", "offset 순서"],
      kind: "broker",
    },
    {
      id: "persistence",
      x: 660,
      y: 300,
      w: 180,
      h: 100,
      title: "Persistence",
      lines: ["중복 저장 방지", "PERSISTED ACK"],
      kind: "transaction",
    },
    {
      id: "fanout",
      x: 660,
      y: 120,
      w: 180,
      h: 100,
      title: "Room Fan-out",
      lines: ["저장 후 fan-out", "room topic"],
      kind: "service",
    },
    {
      id: "receivers",
      x: 900,
      y: 120,
      w: 160,
      h: 100,
      title: "Receivers",
      lines: ["멤버 session", "수신 기록"],
      kind: "external",
    },
    {
      id: "postgres",
      x: 900,
      y: 300,
      w: 160,
      h: 100,
      title: "PostgreSQL",
      lines: ["messageId", "sync 기준"],
      kind: "database",
    },
    {
      id: "reconnect",
      x: 220,
      y: 500,
      w: 180,
      h: 80,
      title: "Reconnect Client",
      lines: ["last messageId"],
      kind: "external",
    },
    {
      id: "syncApi",
      x: 500,
      y: 500,
      w: 180,
      h: 80,
      title: "Sync API",
      lines: ["afterMessageId"],
      kind: "service",
    },
    {
      id: "matrix",
      x: 820,
      y: 500,
      w: 240,
      h: 80,
      title: "Receiver Matrix",
      lines: ["누락 / 중복", "messageId 순서"],
      kind: "note",
    },
  ],
  edges: [
    {
      id: "client-to-subscription",
      from: "client",
      to: "subscription",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 200, y: 240 },
        { x: 200, y: 170 },
      ],
      label: "SUBSCRIBE",
      kind: "sync",
      labelPosition: { x: 300, y: 65 },
    },
    {
      id: "client-to-message-api",
      from: "client",
      to: "messageApi",
      fromPort: "right",
      toPort: "left",
      via: [
        { x: 200, y: 240 },
        { x: 200, y: 350 },
      ],
      label: "SEND",
      kind: "sync",
      labelPosition: { x: 200, y: 430 },
    },
    {
      id: "message-api-to-kafka",
      from: "messageApi",
      to: "kafka",
      fromPort: "right",
      toPort: "left",
      label: "roomId key",
      kind: "async",
      labelPosition: { x: 420, y: 280 },
    },
    {
      id: "kafka-to-persistence",
      from: "kafka",
      to: "persistence",
      fromPort: "right",
      toPort: "left",
      label: "partition order",
      kind: "async",
      labelPosition: { x: 630, y: 430 },
    },
    {
      id: "persistence-to-postgres",
      from: "persistence",
      to: "postgres",
      fromPort: "right",
      toPort: "left",
      label: "save + messageId",
      kind: "sync",
      labelPosition: { x: 870, y: 280 },
    },
    {
      id: "persistence-to-fanout",
      from: "persistence",
      to: "fanout",
      fromPort: "top",
      toPort: "bottom",
      label: "persisted event",
      kind: "async",
      labelPosition: { x: 750, y: 260 },
    },
    {
      id: "fanout-to-receivers",
      from: "fanout",
      to: "receivers",
      fromPort: "right",
      toPort: "left",
      label: "room topic",
      kind: "async",
      labelPosition: { x: 870, y: 100 },
    },
    {
      id: "reconnect-to-sync",
      from: "reconnect",
      to: "syncApi",
      fromPort: "right",
      toPort: "left",
      label: "afterMessageId",
      kind: "sync",
      labelPosition: { x: 450, y: 460 },
    },
    {
      id: "sync-to-postgres",
      from: "syncApi",
      to: "postgres",
      fromPort: "right",
      toPort: "bottom",
      via: [
        { x: 760, y: 540 },
        { x: 760, y: 440 },
        { x: 980, y: 440 },
        { x: 980, y: 400 },
      ],
      label: "누락 구간 조회",
      kind: "sync",
      labelPosition: { x: 740, y: 620 },
    },
    {
      id: "receivers-to-matrix",
      from: "receivers",
      to: "matrix",
      fromPort: "right",
      toPort: "top",
      via: [
        { x: 1080, y: 170 },
        { x: 1080, y: 460 },
        { x: 940, y: 460 },
      ],
      label: "receiver rows",
      kind: "sync",
      labelPosition: { x: 1040, y: 460 },
    },
    {
      id: "postgres-to-matrix",
      from: "postgres",
      to: "matrix",
      fromPort: "bottom",
      toPort: "top",
      via: [
        { x: 980, y: 460 },
        { x: 940, y: 460 },
      ],
      label: "persisted IDs",
      kind: "sync",
      labelPosition: { x: 850, y: 460 },
    },
  ],
} satisfies DiagramSpec;
